
name: Windows Manual Build

on:
  workflow_dispatch:  

jobs:
  windows-build:

    runs-on: windows-2022
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
            arch: x64

      - name: cl.exe should be found now
        run: |
          $(Get-Command cl -ErrorAction SilentlyContinue) -or $(throw "cl.exe wasn't found!")

      - name: Install Boost
        shell: pwsh
        run: |
          .\scripts\install_deps.ps1 vc143
          dir ${{ github.workspace }}\deps\boost\lib\cmake
      
      - name: Install evmone
        shell: pwsh
        run: |
          .\scripts\install_evmone.ps1
          
      - name: Configure Solidity
        run: |
          mkdir ${{ github.workspace }}\build
          dir ${{ github.workspace }}\deps\boost\lib\cmake\Boost-1.74.0
          cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\build\windows-release -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DUSE_Z3=OFF -DUSE_CVC4=OFF -DBoost_DIR=${{ github.workspace }}\deps\boost\lib\cmake\Boost-1.74.0 .

      - name: Build Solidity
        run: |
          cmake --build . --config Release -j 12

      - name: Install Solidity
        run: |
          cmake --install . 

      - name: Upload Artifact 
        uses: actions/upload-artifact@v4
        with:
          name: release-windows
          path: ${{ github.workspace }}\solc

