
name: Windows Manual Build

on:
  workflow_dispatch:  

jobs:
  windows-build:

    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Boost
        shell: pwsh
        run: |
          .\scripts\install_deps.ps1
          dir ${{ github.workspace }}\deps\boost\lib\cmake

          #- name: Install z3
          #shell: pwsh
          #run: |
          #.\scripts\install_z3.ps1
      
      - name: Install evmone
        shell: pwsh
        run: |
          .\scripts\install_evmone.ps1
          

      - name: Configure Solidity
        run: |
          mkdir ${{ github.workspace }}\build
          dir ${{ github.workspace }}\deps\boost\lib\cmake\Boost-1.74.0
          cmake -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\build\windows-release -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DUSE_Z3=OFF -DUSE_CVC4=OFF -DBoost_DIR=${{ github.workspace }}\deps\boost\lib\cmake\Boost-1.74.0 .
          #cmake -G "Visual Studio 17 2022" -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DZ3_DIR="${{ github.workspace }}\build\deps\z3\lib\cmake\z3" -DBoost_DIR="${{ github.workspace }}\build\deps\boost\lib\cmake\Boost-1.78.0" ..

      - name: Build Solidity
        run: |
          cd ${{ github.workspace }}\build
          cmake --build . --config Release -j 12

      - name: Install Solidity
        run: |
          cd ${{ github.workspace }}\build
          cmake --install . 

      - name: Upload Artifact 
        uses: actions/upload-artifact@v3
        with:
          name: release-windows
          path: ${{ github.workspace }}\build


      - name: release 
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/solc/release/solc.exe"
